from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from competition.views import *

urlpatterns = [
    url(r'^create$', Create.as_view()),
    url(r'^detail/(?P<pk>[0-9]+)$', Detail.as_view()),
    url(r'^detail_with_phase/(?P<pk>[0-9]+)$', DetailWithPhase.as_view()),
    url(r'^notice_detail/(?P<pk>[0-9]+)$', NoticeDetail.as_view()),
    url(r'^group_message_detail/(?P<pk>[0-9]+)$', GroupMessageDetail.as_view()),
    url(r'^notice$', GetNotice.as_view()),
    url(r'^notice_status$', NoticeStatus.as_view()),
    url(r'^group_message$', SendGroupMessage.as_view()),
    url(r'^group_message_status$', GroupMessageStatus.as_view()),
    url(r'^receive_group_message$', ReceiveGroupMessage.as_view()),
    url(r'^cover_upload$', CoverUpload.as_view()),
    url(r'^attachment_upload$', AttachmentUpload.as_view()),
    url(r'^submit_upload$', SubmitUpload.as_view()),   
    url(r'^list$', List.as_view()),
    url(r'^home_competition$', HomeCompetition.as_view()),
    url(r'^createPhase$', CreatePhase.as_view()),
    url(r'^detailPhase/(?P<pk>[0-9]+)$', DetailPhase.as_view()),
    url(r'^listPhase$', ListPhase.as_view()),
    url(r'^list_phase_simple$', ListPhaseSimple.as_view()),
    url(r'^team$', GetTeam.as_view()),
    url(r'^team_detail$', TeamDetail.as_view()),
    url(r'^invitation_code$', InvitationCode.as_view()),
    url(r'^create_attachment$', CreateAttachment.as_view()),
    url(r'^list_attachment$', ListAttachment.as_view()),
    url(r'^event_number$', EventNumber.as_view()),
    url(r'^event$', GetEvent.as_view()),
    url(r'^handle_event$', HandleEvent.as_view()),
    url(r'^joiner$', Joiner.as_view()),
    url(r'^joiner_number$', JoinerNumber.as_view()),
    url(r'^joiner_type$', JoinerType.as_view()),
    url(r'^add_joiner$', AddJoiner.as_view()),
    url(r'^grade_number$', GradeNumber.as_view()),
    url(r'^grade$', GetGrade.as_view()),
    url(r'^leader_board$', LeaderBoard.as_view()),
    url(r'^submit_history$', SubmitHistory.as_view()),
    url(r'^handle_grade$', HandleGrade.as_view()),
    url(r'^and_contestant$', AndContestant.as_view()),
    url(r'^enroll$', Enroll.as_view()),
    url(r'^state_update$', StateUpdate.as_view()),
    url(r'^enrolment_info$', EnrolmentInfo.as_view()),
    url(r'^list_contestant$', ListContestant.as_view()),
    url(r'^delete_attachment$', DeleteAttachment.as_view()),
    url(r'^competition_comment$', CreateComment.as_view()),
    url(r'^comment_detail$', CommentDetail.as_view()),
    url(r'^comment_number$', CommentNumber.as_view()),
]

